### PR TITLE
Link zlib statically

### PR DESCRIPTION
**Pull request by jbeich**
Given system zlib support was nuked to fix build within Yuzu stop linking dynamically.

### CODE REVIEW

**Comment by lioncash** [comment]
The purpose of the option is that you can disable it from external scripts. Please don't straight-up remove the option. This makes removing the dependency on a custom fork more of a pain in the future.

**Comment by jbeich** [comment]
@lioncash, removing `option` shouldn't break those. `BUILD_SHARED_LIBS` is handled by CMake itself, see https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html

For one, externals/zlib in Yuzu uses `BUILD_SHARED_LIBS` without exposing via `option`.

**Comment by jbeich** [comment]
OTOH, c23076763369 isn't necessary according to https://github.com/yuzu-emu/yuzu/pull/2947#issuecomment-538701033

**Comment by jbeich** [comment]
Standalone build is broken after be787c219e **unless** `BUILD_SHARED_LIBS` is disabled. Giving this fork is mainly used by Yuzu while upstream is no affected it doesn't look important.
```
$ git clone https://github.com/DarkLordZach/libzip/
$ cd libzip
$ cmake -GNinja .
$ ninja
[112/113] Linking C shared library lib/libzip.so.5.0
FAILED: lib/libzip.so.5.0
: && /usr/bin/cc -fPIC    -shared -Wl,-soname,libzip.so.5 -o lib/libzip.so.5.0 lib/CMakeFiles/zip.dir/zip_add.c.o lib/CMakeFiles/zip.dir/zip_add_dir.c.o lib/CMakeFiles/zip.dir/zip_add_entry.c.o lib/CMakeFiles/zip.dir/zip_algorithm_deflate.c.o lib/CMakeFiles/zip.dir/zip_buffer.c.o lib/CMakeFiles/zip.dir/zip_close.c.o lib/CMakeFiles/zip.dir/zip_delete.c.o lib/CMakeFiles/zip.dir/zip_dir_add.c.o lib/CMakeFiles/zip.dir/zip_dirent.c.o lib/CMakeFiles/zip.dir/zip_discard.c.o lib/CMakeFiles/zip.dir/zip_entry.c.o lib/CMakeFiles/zip.dir/zip_err_str.c.o lib/CMakeFiles/zip.dir/zip_error.c.o lib/CMakeFiles/zip.dir/zip_error_clear.c.o lib/CMakeFiles/zip.dir/zip_error_get.c.o lib/CMakeFiles/zip.dir/zip_error_get_sys_type.c.o lib/CMakeFiles/zip.dir/zip_error_strerror.c.o lib/CMakeFiles/zip.dir/zip_error_to_str.c.o lib/CMakeFiles/zip.dir/zip_extra_field.c.o lib/CMakeFiles/zip.dir/zip_extra_field_api.c.o lib/CMakeFiles/zip.dir/zip_fclose.c.o lib/CMakeFiles/zip.dir/zip_fdopen.c.o lib/CMakeFiles/zip.dir/zip_file_add.c.o lib/CMakeFiles/zip.dir/zip_file_error_clear.c.o lib/CMakeFiles/zip.dir/zip_file_error_get.c.o lib/CMakeFiles/zip.dir/zip_file_get_comment.c.o lib/CMakeFiles/zip.dir/zip_file_get_external_attributes.c.o lib/CMakeFiles/zip.dir/zip_file_get_offset.c.o lib/CMakeFiles/zip.dir/zip_file_rename.c.o lib/CMakeFiles/zip.dir/zip_file_replace.c.o lib/CMakeFiles/zip.dir/zip_file_set_comment.c.o lib/CMakeFiles/zip.dir/zip_file_set_encryption.c.o lib/CMakeFiles/zip.dir/zip_file_set_external_attributes.c.o lib/CMakeFiles/zip.dir/zip_file_set_mtime.c.o lib/CMakeFiles/zip.dir/zip_file_strerror.c.o lib/CMakeFiles/zip.dir/zip_filerange_crc.c.o lib/CMakeFiles/zip.dir/zip_fopen.c.o lib/CMakeFiles/zip.dir/zip_fopen_encrypted.c.o lib/CMakeFiles/zip.dir/zip_fopen_index.c.o lib/CMakeFiles/zip.dir/zip_fopen_index_encrypted.c.o lib/CMakeFiles/zip.dir/zip_fread.c.o lib/CMakeFiles/zip.dir/zip_fseek.c.o lib/CMakeFiles/zip.dir/zip_ftell.c.o lib/CMakeFiles/zip.dir/zip_get_archive_comment.c.o lib/CMakeFiles/zip.dir/zip_get_archive_flag.c.o lib/CMakeFiles/zip.dir/zip_get_encryption_implementation.c.o lib/CMakeFiles/zip.dir/zip_get_file_comment.c.o lib/CMakeFiles/zip.dir/zip_get_name.c.o lib/CMakeFiles/zip.dir/zip_get_num_entries.c.o lib/CMakeFiles/zip.dir/zip_get_num_files.c.o lib/CMakeFiles/zip.dir/zip_hash.c.o lib/CMakeFiles/zip.dir/zip_io_util.c.o lib/CMakeFiles/zip.dir/zip_libzip_version.c.o lib/CMakeFiles/zip.dir/zip_memdup.c.o lib/CMakeFiles/zip.dir/zip_name_locate.c.o lib/CMakeFiles/zip.dir/zip_new.c.o lib/CMakeFiles/zip.dir/zip_open.c.o lib/CMakeFiles/zip.dir/zip_progress.c.o lib/CMakeFiles/zip.dir/zip_rename.c.o lib/CMakeFiles/zip.dir/zip_replace.c.o lib/CMakeFiles/zip.dir/zip_set_archive_comment.c.o lib/CMakeFiles/zip.dir/zip_set_archive_flag.c.o lib/CMakeFiles/zip.dir/zip_set_default_password.c.o lib/CMakeFiles/zip.dir/zip_set_file_comment.c.o lib/CMakeFiles/zip.dir/zip_set_file_compression.c.o lib/CMakeFiles/zip.dir/zip_set_name.c.o lib/CMakeFiles/zip.dir/zip_source_begin_write.c.o lib/CMakeFiles/zip.dir/zip_source_begin_write_cloning.c.o lib/CMakeFiles/zip.dir/zip_source_buffer.c.o lib/CMakeFiles/zip.dir/zip_source_call.c.o lib/CMakeFiles/zip.dir/zip_source_close.c.o lib/CMakeFiles/zip.dir/zip_source_commit_write.c.o lib/CMakeFiles/zip.dir/zip_source_compress.c.o lib/CMakeFiles/zip.dir/zip_source_crc.c.o lib/CMakeFiles/zip.dir/zip_source_error.c.o lib/CMakeFiles/zip.dir/zip_source_filep.c.o lib/CMakeFiles/zip.dir/zip_source_free.c.o lib/CMakeFiles/zip.dir/zip_source_function.c.o lib/CMakeFiles/zip.dir/zip_source_get_compression_flags.c.o lib/CMakeFiles/zip.dir/zip_source_is_deleted.c.o lib/CMakeFiles/zip.dir/zip_source_layered.c.o lib/CMakeFiles/zip.dir/zip_source_open.c.o lib/CMakeFiles/zip.dir/zip_source_pkware.c.o lib/CMakeFiles/zip.dir/zip_source_read.c.o lib/CMakeFiles/zip.dir/zip_source_remove.c.o lib/CMakeFiles/zip.dir/zip_source_rollback_write.c.o lib/CMakeFiles/zip.dir/zip_source_seek.c.o lib/CMakeFiles/zip.dir/zip_source_seek_write.c.o lib/CMakeFiles/zip.dir/zip_source_stat.c.o lib/CMakeFiles/zip.dir/zip_source_supports.c.o lib/CMakeFiles/zip.dir/zip_source_tell.c.o lib/CMakeFiles/zip.dir/zip_source_tell_write.c.o lib/CMakeFiles/zip.dir/zip_source_window.c.o lib/CMakeFiles/zip.dir/zip_source_write.c.o lib/CMakeFiles/zip.dir/zip_source_zip.c.o lib/CMakeFiles/zip.dir/zip_source_zip_new.c.o lib/CMakeFiles/zip.dir/zip_stat.c.o lib/CMakeFiles/zip.dir/zip_stat_index.c.o lib/CMakeFiles/zip.dir/zip_stat_init.c.o lib/CMakeFiles/zip.dir/zip_strerror.c.o lib/CMakeFiles/zip.dir/zip_string.c.o lib/CMakeFiles/zip.dir/zip_unchange.c.o lib/CMakeFiles/zip.dir/zip_unchange_all.c.o lib/CMakeFiles/zip.dir/zip_unchange_archive.c.o lib/CMakeFiles/zip.dir/zip_unchange_data.c.o lib/CMakeFiles/zip.dir/zip_utf-8.c.o lib/CMakeFiles/zip.dir/zip_crypto_gnutls.c.o lib/CMakeFiles/zip.dir/zip_winzip_aes.c.o lib/CMakeFiles/zip.dir/zip_source_winzip_aes_decode.c.o lib/CMakeFiles/zip.dir/zip_source_winzip_aes_encode.c.o lib/CMakeFiles/zip.dir/zip_source_file.c.o  -Wl,-rpath,/usr/local/lib -lzlib /usr/local/lib/libgnutls.so /usr/local/lib/libnettle.so && :
ld: error: unable to find library -lzlib
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by jbeich** [comment]
This repo is not used after yuzu-emu/yuzu@1643af431c50.

**Pull request closed without merging**
